notifications:
  slack:
    secure: n+iMNg8JMaKKrrylXm6o/plV7jKc9aprfd9mFGdZSwvvcTLGeetGmUnR29UYLL5gX6kITQW5QdAE67mI/aTiUOuCmgWcPVyPzbLQg7fCFyeFfC2zAwm2ku9xLjsyzAKCSA0DQ9DGgND1FyN5S/Zuy9k8W1ISpt6ZHeMaj4Go3n4n+sf8QvpDYGkr06i3qm8lo42SPIgIpV41CjZC16KHuKZz7BbQZz1z8fCJ0SBy8J8S/opYNKsnrFMPNlJgs6TlwEZEG7xMkxfiMg9fjDBQ+44vrEofWLexjSFXrbhQxX7deoSg3HvfPnBNH+aT2PpYHdKVSRAikbWYmuxxnYWCyXf4VfLAi46dhmPVzRHZOC+CkO1Cj7qAcH6itXB/Qg3P1abX5zJzViskheb/ZQ9ZsqqaXvRWwgyxIh86ORK87jP5UxeaHFjuCViOwJVnxiCZ9k6a1iJSXuJNslTZhiE3UMwMd6838IyGLQdD/l3RxR48O9zvoLo7RcMYgodX4b4GaquXe9RLcIR8Tx8FRDvbkmHQg1075Dm1T+DFVa56KnALkUKfpGsQjBzgYcfaa4spQJlhpIpxuIUJMUHeUI46Jww47OKrO+9CvN4dYCX0ImR4glsAQS/SWIRnjabvn5XvW3T+X97pdRqzUhlv4K6JGah1tUk5JITIqGusbvIP1Yw=
language: node_js
sudo: required
os:
  - linux
node_js:
  - "6"
  - "6.1"
  - "5.11"
services:
  - redis-server
before_install:
  - cp config/conf.example.yaml config/conf.yaml
install:
  - npm install -g yarn
  - yarn install
script:
  - npm test
